# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/dev/satelit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/dev/satelit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/satelit/CMakeFiles /mnt/c/dev/satelit/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/dev/satelit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named satelit

# Build rule for target.
satelit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 satelit
.PHONY : satelit

# fast build rule for target.
satelit/fast:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/build
.PHONY : satelit/fast

#=============================================================================
# Target rules for targets named satelit_tests

# Build rule for target.
satelit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 satelit_tests
.PHONY : satelit_tests

# fast build rule for target.
satelit_tests/fast:
	$(MAKE) -f tests/CMakeFiles/satelit_tests.dir/build.make tests/CMakeFiles/satelit_tests.dir/build
.PHONY : satelit_tests/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

antlr4cpp_generated_src/TLexer/TLexer.o: antlr4cpp_generated_src/TLexer/TLexer.cpp.o

.PHONY : antlr4cpp_generated_src/TLexer/TLexer.o

# target to build an object file
antlr4cpp_generated_src/TLexer/TLexer.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.o
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.cpp.o

antlr4cpp_generated_src/TLexer/TLexer.i: antlr4cpp_generated_src/TLexer/TLexer.cpp.i

.PHONY : antlr4cpp_generated_src/TLexer/TLexer.i

# target to preprocess a source file
antlr4cpp_generated_src/TLexer/TLexer.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.i
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.cpp.i

antlr4cpp_generated_src/TLexer/TLexer.s: antlr4cpp_generated_src/TLexer/TLexer.cpp.s

.PHONY : antlr4cpp_generated_src/TLexer/TLexer.s

# target to generate assembly for a file
antlr4cpp_generated_src/TLexer/TLexer.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TLexer/TLexer.cpp.s
.PHONY : antlr4cpp_generated_src/TLexer/TLexer.cpp.s

antlr4cpp_generated_src/TParser/TParser.o: antlr4cpp_generated_src/TParser/TParser.cpp.o

.PHONY : antlr4cpp_generated_src/TParser/TParser.o

# target to build an object file
antlr4cpp_generated_src/TParser/TParser.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParser.cpp.o
.PHONY : antlr4cpp_generated_src/TParser/TParser.cpp.o

antlr4cpp_generated_src/TParser/TParser.i: antlr4cpp_generated_src/TParser/TParser.cpp.i

.PHONY : antlr4cpp_generated_src/TParser/TParser.i

# target to preprocess a source file
antlr4cpp_generated_src/TParser/TParser.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParser.cpp.i
.PHONY : antlr4cpp_generated_src/TParser/TParser.cpp.i

antlr4cpp_generated_src/TParser/TParser.s: antlr4cpp_generated_src/TParser/TParser.cpp.s

.PHONY : antlr4cpp_generated_src/TParser/TParser.s

# target to generate assembly for a file
antlr4cpp_generated_src/TParser/TParser.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParser.cpp.s
.PHONY : antlr4cpp_generated_src/TParser/TParser.cpp.s

antlr4cpp_generated_src/TParser/TParserBaseVisitor.o: antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.o

.PHONY : antlr4cpp_generated_src/TParser/TParserBaseVisitor.o

# target to build an object file
antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.o
.PHONY : antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.o

antlr4cpp_generated_src/TParser/TParserBaseVisitor.i: antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.i

.PHONY : antlr4cpp_generated_src/TParser/TParserBaseVisitor.i

# target to preprocess a source file
antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.i
.PHONY : antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.i

antlr4cpp_generated_src/TParser/TParserBaseVisitor.s: antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.s

.PHONY : antlr4cpp_generated_src/TParser/TParserBaseVisitor.s

# target to generate assembly for a file
antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.s
.PHONY : antlr4cpp_generated_src/TParser/TParserBaseVisitor.cpp.s

antlr4cpp_generated_src/TParser/TParserVisitor.o: antlr4cpp_generated_src/TParser/TParserVisitor.cpp.o

.PHONY : antlr4cpp_generated_src/TParser/TParserVisitor.o

# target to build an object file
antlr4cpp_generated_src/TParser/TParserVisitor.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParserVisitor.cpp.o
.PHONY : antlr4cpp_generated_src/TParser/TParserVisitor.cpp.o

antlr4cpp_generated_src/TParser/TParserVisitor.i: antlr4cpp_generated_src/TParser/TParserVisitor.cpp.i

.PHONY : antlr4cpp_generated_src/TParser/TParserVisitor.i

# target to preprocess a source file
antlr4cpp_generated_src/TParser/TParserVisitor.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParserVisitor.cpp.i
.PHONY : antlr4cpp_generated_src/TParser/TParserVisitor.cpp.i

antlr4cpp_generated_src/TParser/TParserVisitor.s: antlr4cpp_generated_src/TParser/TParserVisitor.cpp.s

.PHONY : antlr4cpp_generated_src/TParser/TParserVisitor.s

# target to generate assembly for a file
antlr4cpp_generated_src/TParser/TParserVisitor.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/antlr4cpp_generated_src/TParser/TParserVisitor.cpp.s
.PHONY : antlr4cpp_generated_src/TParser/TParserVisitor.cpp.s

src/compile_visitor.o: src/compile_visitor.cpp.o

.PHONY : src/compile_visitor.o

# target to build an object file
src/compile_visitor.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/compile_visitor.cpp.o
.PHONY : src/compile_visitor.cpp.o

src/compile_visitor.i: src/compile_visitor.cpp.i

.PHONY : src/compile_visitor.i

# target to preprocess a source file
src/compile_visitor.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/compile_visitor.cpp.i
.PHONY : src/compile_visitor.cpp.i

src/compile_visitor.s: src/compile_visitor.cpp.s

.PHONY : src/compile_visitor.s

# target to generate assembly for a file
src/compile_visitor.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/compile_visitor.cpp.s
.PHONY : src/compile_visitor.cpp.s

src/data_types/variable_map.o: src/data_types/variable_map.cpp.o

.PHONY : src/data_types/variable_map.o

# target to build an object file
src/data_types/variable_map.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/data_types/variable_map.cpp.o
.PHONY : src/data_types/variable_map.cpp.o

src/data_types/variable_map.i: src/data_types/variable_map.cpp.i

.PHONY : src/data_types/variable_map.i

# target to preprocess a source file
src/data_types/variable_map.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/data_types/variable_map.cpp.i
.PHONY : src/data_types/variable_map.cpp.i

src/data_types/variable_map.s: src/data_types/variable_map.cpp.s

.PHONY : src/data_types/variable_map.s

# target to generate assembly for a file
src/data_types/variable_map.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/data_types/variable_map.cpp.s
.PHONY : src/data_types/variable_map.cpp.s

src/interpreter.o: src/interpreter.cpp.o

.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/interpreter.cpp.o
.PHONY : src/interpreter.cpp.o

src/interpreter.i: src/interpreter.cpp.i

.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/interpreter.cpp.i
.PHONY : src/interpreter.cpp.i

src/interpreter.s: src/interpreter.cpp.s

.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/interpreter.cpp.s
.PHONY : src/interpreter.cpp.s

src/runtime_visitor.o: src/runtime_visitor.cpp.o

.PHONY : src/runtime_visitor.o

# target to build an object file
src/runtime_visitor.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/runtime_visitor.cpp.o
.PHONY : src/runtime_visitor.cpp.o

src/runtime_visitor.i: src/runtime_visitor.cpp.i

.PHONY : src/runtime_visitor.i

# target to preprocess a source file
src/runtime_visitor.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/runtime_visitor.cpp.i
.PHONY : src/runtime_visitor.cpp.i

src/runtime_visitor.s: src/runtime_visitor.cpp.s

.PHONY : src/runtime_visitor.s

# target to generate assembly for a file
src/runtime_visitor.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/runtime_visitor.cpp.s
.PHONY : src/runtime_visitor.cpp.s

src/stack_machine.o: src/stack_machine.cpp.o

.PHONY : src/stack_machine.o

# target to build an object file
src/stack_machine.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/stack_machine.cpp.o
.PHONY : src/stack_machine.cpp.o

src/stack_machine.i: src/stack_machine.cpp.i

.PHONY : src/stack_machine.i

# target to preprocess a source file
src/stack_machine.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/stack_machine.cpp.i
.PHONY : src/stack_machine.cpp.i

src/stack_machine.s: src/stack_machine.cpp.s

.PHONY : src/stack_machine.s

# target to generate assembly for a file
src/stack_machine.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/stack_machine.cpp.s
.PHONY : src/stack_machine.cpp.s

src/stfunction.o: src/stfunction.cpp.o

.PHONY : src/stfunction.o

# target to build an object file
src/stfunction.cpp.o:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/stfunction.cpp.o
.PHONY : src/stfunction.cpp.o

src/stfunction.i: src/stfunction.cpp.i

.PHONY : src/stfunction.i

# target to preprocess a source file
src/stfunction.cpp.i:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/stfunction.cpp.i
.PHONY : src/stfunction.cpp.i

src/stfunction.s: src/stfunction.cpp.s

.PHONY : src/stfunction.s

# target to generate assembly for a file
src/stfunction.cpp.s:
	$(MAKE) -f CMakeFiles/satelit.dir/build.make CMakeFiles/satelit.dir/src/stfunction.cpp.s
.PHONY : src/stfunction.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... satelit"
	@echo "... satelit_tests"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... antlr4cpp_generated_src/TLexer/TLexer.o"
	@echo "... antlr4cpp_generated_src/TLexer/TLexer.i"
	@echo "... antlr4cpp_generated_src/TLexer/TLexer.s"
	@echo "... antlr4cpp_generated_src/TParser/TParser.o"
	@echo "... antlr4cpp_generated_src/TParser/TParser.i"
	@echo "... antlr4cpp_generated_src/TParser/TParser.s"
	@echo "... antlr4cpp_generated_src/TParser/TParserBaseVisitor.o"
	@echo "... antlr4cpp_generated_src/TParser/TParserBaseVisitor.i"
	@echo "... antlr4cpp_generated_src/TParser/TParserBaseVisitor.s"
	@echo "... antlr4cpp_generated_src/TParser/TParserVisitor.o"
	@echo "... antlr4cpp_generated_src/TParser/TParserVisitor.i"
	@echo "... antlr4cpp_generated_src/TParser/TParserVisitor.s"
	@echo "... src/compile_visitor.o"
	@echo "... src/compile_visitor.i"
	@echo "... src/compile_visitor.s"
	@echo "... src/data_types/variable_map.o"
	@echo "... src/data_types/variable_map.i"
	@echo "... src/data_types/variable_map.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/runtime_visitor.o"
	@echo "... src/runtime_visitor.i"
	@echo "... src/runtime_visitor.s"
	@echo "... src/stack_machine.o"
	@echo "... src/stack_machine.i"
	@echo "... src/stack_machine.s"
	@echo "... src/stfunction.o"
	@echo "... src/stfunction.i"
	@echo "... src/stfunction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

